import type { PronosticSession, DashboardStats, MonthlyStats } from './types'

const now = Date.now()
const today = new Date(now).toISOString().split('T')[0]
const yesterday = new Date(now - 86400000).toISOString().split('T')[0]
const twoDaysAgo = new Date(now - 172800000).toISOString().split('T')[0]

export const mockSessions: PronosticSession[] = [
  {
    id: '1',
    date: today,
    status: 'draft',
    combined_odds: 3.24,
    published_at: null,
    telegram_msg_id: null,
    notes: 'Forte tendance défensive identifiée sur Arsenal et Lyon ce soir.',
    created_at: new Date(now - 2 * 3600000).toISOString(),
    picks: [
      {
        id: 'p1',
        session_id: '1',
        competition: 'Premier League',
        home_team: 'Arsenal',
        away_team: 'Chelsea',
        bet_type: 'Moins de 3.5 buts',
        odds: 1.55,
        trend_label: 'Arsenal: 13/15 derniers matchs sous 3.5 buts',
        trend_pct: 86.7,
        sample_size: 15,
        match_datetime: new Date(now + 4 * 3600000).toISOString(),
        result: null,
        created_at: new Date(now - 2 * 3600000).toISOString(),
      },
      {
        id: 'p2',
        session_id: '1',
        competition: 'Ligue 1',
        home_team: 'PSG',
        away_team: 'Lyon',
        bet_type: 'BTTS Non',
        odds: 2.09,
        trend_label: 'Lyon: 10/11 derniers déplacements sans marquer',
        trend_pct: 90.9,
        sample_size: 11,
        match_datetime: new Date(now + 6 * 3600000).toISOString(),
        result: null,
        created_at: new Date(now - 2 * 3600000).toISOString(),
      },
    ],
  },
  {
    id: '2',
    date: yesterday,
    status: 'published',
    combined_odds: 4.59,
    published_at: new Date(now - 22 * 3600000).toISOString(),
    telegram_msg_id: '8471',
    notes: '3 tendances solides — session publiée avec succès.',
    created_at: new Date(now - 24 * 3600000).toISOString(),
    picks: [
      {
        id: 'p3',
        session_id: '2',
        competition: 'Bundesliga',
        home_team: 'Bayern Munich',
        away_team: 'Dortmund',
        bet_type: 'Plus de 2.5 buts',
        odds: 1.70,
        trend_label: 'Classico: 9/10 derbys Bayern-Dortmund avec +2.5 buts',
        trend_pct: 90.0,
        sample_size: 10,
        match_datetime: new Date(now - 26 * 3600000).toISOString(),
        result: 'win',
        created_at: new Date(now - 24 * 3600000).toISOString(),
      },
      {
        id: 'p4',
        session_id: '2',
        competition: 'La Liga',
        home_team: 'Real Madrid',
        away_team: 'Atletico Madrid',
        bet_type: 'Moins de 2.5 buts',
        odds: 1.75,
        trend_label: 'Derby Madrid: 8/9 confrontations sous 2.5 buts',
        trend_pct: 88.9,
        sample_size: 9,
        match_datetime: new Date(now - 27 * 3600000).toISOString(),
        result: 'win',
        created_at: new Date(now - 24 * 3600000).toISOString(),
      },
      {
        id: 'p5',
        session_id: '2',
        competition: 'Serie A',
        home_team: 'Inter Milan',
        away_team: 'Napoli',
        bet_type: 'Victoire Inter Milan',
        odds: 1.95,
        trend_label: 'Inter Milan: 11/13 victoires à domicile cette saison',
        trend_pct: 84.6,
        sample_size: 13,
        match_datetime: new Date(now - 28 * 3600000).toISOString(),
        result: 'loss',
        created_at: new Date(now - 24 * 3600000).toISOString(),
      },
    ],
  },
  {
    id: '3',
    date: twoDaysAgo,
    status: 'published',
    combined_odds: 2.97,
    published_at: new Date(now - 46 * 3600000).toISOString(),
    telegram_msg_id: '8312',
    notes: null,
    created_at: new Date(now - 48 * 3600000).toISOString(),
    picks: [
      {
        id: 'p6',
        session_id: '3',
        competition: 'Premier League',
        home_team: 'Manchester City',
        away_team: 'Liverpool',
        bet_type: 'Moins de 3.5 buts',
        odds: 1.55,
        trend_label: 'Man City à domicile: 12/14 matchs sous 3.5 buts',
        trend_pct: 85.7,
        sample_size: 14,
        match_datetime: new Date(now - 50 * 3600000).toISOString(),
        result: 'win',
        created_at: new Date(now - 48 * 3600000).toISOString(),
      },
      {
        id: 'p7',
        session_id: '3',
        competition: 'Ligue 1',
        home_team: 'Marseille',
        away_team: 'Nice',
        bet_type: 'Marseille Victoire',
        odds: 1.92,
        trend_label: 'Marseille: 9/10 victoires à domicile au Vélodrome',
        trend_pct: 90.0,
        sample_size: 10,
        match_datetime: new Date(now - 50 * 3600000).toISOString(),
        result: 'win',
        created_at: new Date(now - 48 * 3600000).toISOString(),
      },
    ],
  },
]

export const mockStats: DashboardStats = {
  total_this_month: 18,
  win_rate: 72.7,
  pending_review: 1,
  published_today: 0,
  current_streak: 4,
  roi_this_month: 14.8,
}

export const mockMonthlyStats: MonthlyStats[] = [
  { month: 'Fév', total: 12, wins: 8, losses: 3, voids: 1, win_rate: 66.7, roi: 9.2 },
  { month: 'Mar', total: 15, wins: 10, losses: 4, voids: 1, win_rate: 66.7, roi: 10.4 },
  { month: 'Avr', total: 18, wins: 13, losses: 4, voids: 1, win_rate: 72.2, roi: 16.8 },
  { month: 'Mai', total: 14, wins: 10, losses: 3, voids: 1, win_rate: 71.4, roi: 13.5 },
  { month: 'Jun', total: 11, wins: 8, losses: 2, voids: 1, win_rate: 72.7, roi: 12.1 },
  { month: 'Jul', total: 18, wins: 13, losses: 4, voids: 1, win_rate: 72.7, roi: 14.8 },
]
